[project]
name = "ai21-maestro-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ai21>=4.2.0",
    "fastmcp>=2.12.5",
    "ipykernel>=7.0.1",
]
